apiVersion: jenkins.io/v1
kind: SourceRepository
metadata:
  annotations:
    jenkins.io/last-build-number-for-master: "3"
  creationTimestamp: null
  labels:
    owner: nxmatic
    provider: github
    repository: jxlabs-nos-jenkins-quickstart
  name: nxmatic-jxlabs-nos-jenkins-quickstart
spec:
  description: Imported application for nxmatic/jxlabs-nos-jenkins-quickstart
  httpCloneURL: https://github.com/nxmatic/jxlabs-nos-jenkins-quickstart.git
  org: nxmatic
  provider: https://github.com
  providerKind: github
  providerName: github
  repo: jxlabs-nos-jenkins-quickstart
  scheduler:
    kind: ""
    name: ""
  url: https://github.com/nxmatic/jxlabs-nos-jenkins-quickstart.git
